### ISSUE TITLE
[Bug] ERROR: Something went wrong in @nrwl/run-commands - Command failed: flutter install

### ISSUE THREAD

**Issue by nerddigestive** [tinesoft/nxrocks#105] opened 2022-04-05 15:03 UTC
### Plugin Name

@nxrocks/nx-flutter

### Plugin Version

v3.0.2

### Nx Version

13.9.6

### Expected Behaviour

Commands such as `nx run myapp:build` run (as when run manually) and produce output.

### Actual Behaviour

All flutter commands run using `run-commands` throw the following error, with no further output:

`ERROR: Something went wrong in @nrwl/run-commands - Command failed: flutter install`

When the verbose flag is provided, we get:

```
Error: ERROR: Something went wrong in @nrwl/run-commands - Command failed: flutter doctor
    at /home/edhill/Code/brightsign/brightsign/node_modules/@nrwl/workspace/src/executors/run-commands/run-commands.impl.js:54:19
    at Generator.throw (<anonymous>)
    at rejected (/home/edhill/Code/brightsign/brightsign/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

All of these commands run perfectly fine when run by hand in the app directory. All of these commands also run fine when wrapped like `echo $(flutter install)`.

### Steps to reproduce the behaviour

0. With `flutter` installed and working correctly system-wide
1. Create a new NX workspace.
2. Install the nx-flutter package.
3. Create a new flutter app (I have been testing with Android and iOS primarily)
4. Attempt to run `nx run myapp:xxxx`

**Comment by tinesoft** [comment] 2022-07-29 09:17
Hi @nerddigestive 

Thanks for using the plugin and for reporting the issue. Unfortunately i cannot reproduce it...
Can you share a repro project ?

Thanks

**Comment by tinesoft** [comment] 2022-10-23 09:19
Closing for now, feel free to re-open (with repo project if possible) if the issue still occurs

**Closed by tinesoft** 2022-10-23 09:19 UTC
Labels: @nxrocks/nx-flutter, pending approval/feedback
