### ISSUE TITLE
[Bug] Dep Graphs not working

### ISSUE THREAD

**Issue by SOG-web** [tinesoft/nxrocks#150] opened 2022-12-03 10:08 UTC
### Plugin Name

@nxrocks/nx-flutter

### Plugin Version

v5.0.0

### Nx Version

15.2.4

### Expected Behaviour

I expect it to show the link between each and the lib they are related to or using

### Actual Behaviour

It not showing the linking

### Steps to reproduce the behaviour

1. Generate a new nx workspace
2. Add nx-flutter
3. Generate a new flutter app
4. Generate new flutter lib
5. Add the flutter lib path to your app `pubspec.yaml`
6. Run nx dep graph

or try this script
```ts
import {
  getPackageManagerCommand,
  readCachedProjectGraph,
  workspaceRoot,
  Workspaces,
} from '@nrwl/devkit';
import { execSync } from 'child_process';

const workspace = new Workspaces(workspaceRoot).readWorkspaceConfiguration();
const pmc = getPackageManagerCommand();
const graph = readCachedProjectGraph();

function findRelatedProjects(project: string): Set<string> {
  const output = new Set<string>();

  const dependenciesToCheck: string[] = [project];

  while (dependenciesToCheck.length) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const dep = dependenciesToCheck.shift()!;
    console.log(dep);

    console.log(graph.dependencies[dep]);

    for (const d of graph.dependencies[dep]) {
      console.log(graph.dependencies[dep].length);
      console.log(d.target);
    }
  }

  // console.log(output);

  return output;
}
```

**Comment by tinesoft** [comment] 2022-12-04 08:26
Hi @SOG-web,

Can you post the content of your `pubspec.yaml` files  (for the app and the lib)?

**Comment by dubemarcantoine** [comment] 2022-12-06 04:18
Hi! I have the same issue, the plugin does not seem to work with nx-quarkus.
I imported `lib2` in `test-app`, but they are separated in the graph.
![Screenshot_3](https://user-images.githubusercontent.com/11211814/205812443-6bbf8d54-a372-4a66-9aca-e343743c2041.png)

I created this project to demonstrate: https://github.com/dubemarcantoine/nx-quarkus-debugging

Thanks for your help!

**Comment by SOG-web** [comment] 2022-12-07 10:09
pubspec for app
```yaml
name: test_app
description: test-app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  test:
    path: '../../libs/test'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
```

pubspec for lib
```yaml
name: test
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
```

Thanks so much

**Comment by SOG-web** [comment] 2023-01-03 14:54
Hi, Happy new year to you.

Thanks for building this package for us to use.

I just wanted to check if this issue has been solved.

Thanks so much for the effort

**Comment by tinesoft** [comment] 2023-01-04 18:33
Hi @SOG-web ,

Thank you, happy new year to you as well, all the best for the new year!

No worry, this issue is still my top priority. I'll let you know here as soon as it is fixed.

**Comment by tinesoft** [comment] 2023-01-07 20:48
@dubemarcantoine  The dependency problem with nx-quarkus was fixed by https://github.com/tinesoft/nxrocks/commit/2ada704f17bdf4a2bec5314b1faf2147c460e4b2 . It should be released very soon

@SOG-web : I wasn't able to reproduce the problem for nx-flutter...it works as expected with the two samples of  `pubspec.yaml` you provided...

Do you have a repro project I can rely on? or can you create one?
Thanks

**Comment by dubemarcantoine** [comment] 2023-01-07 21:35
Hi @tinesoft ! Happy New Year!
Thank you so much, I will have a look once the latest version of Quarkus comes out :grin:

**Comment by tinesoft** [comment] 2023-01-10 23:27
@dubemarcantoine   https://github.com/tinesoft/nxrocks/releases/tag/nx-quarkus%2Fv4.2.0 was released and it should fix the issue for quarkus

@SOG-web  i will close the ticket as I was not able to reproduce for nx-flutter....

**Closed by tinesoft** 2023-01-10 23:27 UTC
Labels: @nxrocks/nx-flutter, pending approval/feedback
