### ISSUE TITLE
[Bug] The string contains invalid characters. when extracting Spring Boot project

### ISSUE THREAD

**Issue by ProfEibe** [tinesoft/nxrocks#102] opened 2022-03-23 16:40 UTC
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

v4.0.2

### Nx Version

12.10.1

### Expected Behaviour

creating SpringBoot Project

### Actual Behaviour

```
Extracting Spring Boot project zip to 'C:\nennungenRest/apps/rest'...
The string contains invalid characters.
```

### Steps to reproduce the behaviour

When generating a new project I get the error above while downloading and extracting from start.spring.io

**Comment by tinesoft** [comment] 2022-03-25 06:00
Hi @ProfEibe ,

Thanks for using the plugin, and reporting the issue.
Can you please, provide all the parameters you set when generating the app? (i.e application name, build type,  java version, etc)

**Comment by ProfEibe** [comment] 2022-03-25 10:29
This is the whole part in the console:

```
> Executing task: npx nx generate @nxrocks/nx-spring-boot:project --name=SGNennungen-Rest --artifactId=SGNennungen-Rest --dependencies=web --descriptionwarzgold --packageName=at.schwarzgold.sgnennungen.rest --no-interactive <

Downloading Spring Boot project zip from : https://start.spring.io/starter.zip?type=maven-project&language=java&name=SGNennungen-Rest&groupId=at.schwarzackageName=at.schwarzgold.sgnennungen.rest&javaVersion=11&packaging=jar&dependencies=web&description=SGNennungen-Rest...
Extracting Spring Boot project zip to 'C:\Users\Jakob\IdeaProjects\nennungen-rest/apps/sgnennungen-rest'...
The string contains invalid characters. 
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npx nx generate @nxrocks/nx-spring-boot:project --name=SGNennunRest --dependencies=web --description=SGNennungen-Rest --groupId=at.schwarzgold --packageName=at.schwarzgold.sgnennungen.rest --no-interactive" terminat
```

**Comment by tinesoft** [comment] 2022-03-27 06:10
Thanks for the detailed log output.
Unfortunately, I cannot reproduce the issue with the parameters you provided...

Could you try generating an app without changing the default parameters of the generator (i.e by just pressing "Enter" at each prompt)? Also, what version of NodeJS are you using? (`node --version`)

**Comment by ProfEibe** [comment] 2022-03-27 18:57
Hm sadly the same problem.
Maybe it is, because the generated springboot-app would be the first in this repository?
Because creating one in an nx-workspace where already an angular-app exists is working without any error. But in an empty nx-workspace I get this error.

Node-Version is 16.14.2

**Comment by tinesoft** [comment] 2022-03-27 22:00
I've just noticed you are using a version of Nx (v12) which is not compatible with current version of the nx-spring-boot plugin (v4).  See [compatibility matrix](https://github.com/tinesoft/nxrocks/blob/develop/packages/nx-spring-boot/README.md#compatibility-with-nx)

Please update your Nx workspace and try again.

Closing the issue for now.

**Closed** 2022-03-27 22:00 UTC
Labels: :bug: bug

**Comment by ProfEibe** [comment] 2022-03-28 07:02
Oh... I'm sorry for bothering you. Should have seen this myself.
Maybe someone could build in a check with an speaking error message for this, but it was clearly my fault this time.

Thanks for your support.
