### ISSUE TITLE
[Bug] create command fails with error "Cannot find module '@nrwl/workspace/src/utils/fileutils'"

### ISSUE THREAD

**Issue by jcassee** [tinesoft/nxrocks#154] opened 2022-12-07 21:09 UTC
### Plugin Name

@nxrocks/nx-flutter

### Plugin Version

v5.1.0

### Nx Version

15.3.0

### Expected Behaviour

I tried to create a flutter application using the `create` command:
```
npx nx g @nxrocks/nx-flutter:create flutter-test
```

I had expected it to create a flutter application.

### Actual Behaviour

```bash
>  NX  Generating @nxrocks/nx-flutter:project

✔ What package name would you like to use? · com.example
✔ What is the project about? · Example
✔ Which type of Flutter project would you like to create? · app

 >  NX   Cannot find module '@nrwl/workspace/src/utils/fileutils'

   Require stack:
   - PROJECT_PATH/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js
   - PROJECT_PATH/node_modules/@nxrocks/common/src/lib/core/jvm/index.js
   - PROJECT_PATH/node_modules/@nxrocks/common/src/index.js
   - PROJECT_PATH/node_modules/@nxrocks/nx-flutter/src/generators/project/generator.js
   - PROJECT_PATH/node_modules/nx/src/config/workspaces.js
   - PROJECT_PATH/node_modules/nx/src/config/configuration.js
   - PROJECT_PATH/node_modules/nx/src/command-line/generate.js
   - PROJECT_PATH/node_modules/nx/src/command-line/nx-commands.js
   - PROJECT_PATH/node_modules/nx/bin/init-local.js
   - PROJECT_PATH/node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```

### Steps to reproduce the behaviour

1. Create an nx project.
2. Install nx-flutter
3. Run create command

**Comment by jcassee** [comment] 2022-12-07 21:11
I checked old bug reports. #37 looks similar, but is closed as fixed.

**Comment by tinesoft** [comment] 2023-01-13 22:03
Hi @jcassee 

Sorry for the delay in responding... I totally missed this issue.
Are you still having the problem ? I cannot reproduce it...

**Comment by tinesoft** [comment] 2023-03-15 05:14
Closing for now, Feel free to re-open, if issue is still relevant

**Closed by tinesoft** 2023-03-15 05:14 UTC
Labels: pending approval/feedback

**Comment by jcassee** [comment] 2023-03-24 09:00
Sorry for the long silence, but just to confirm: I have not had this problem since upgrading to Nx 15.7+.

**Comment by trondeh80** [comment] 2023-10-21 09:58
I got the same problem today. Having this in my workspace (running in WSL 2):
   Node   : 21.0.0
   OS     : linux-x64
   npm    : 10.2.0

   nx (global)        : 17.0.1
   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/jest           : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nx/next           : 17.0.1
   @nx/playwright     : 17.0.1
   @nx/react          : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/web            : 17.0.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nxrocks/nx-spring-boot : 8.1.0

When I try to generate the spring boot application. It fails with the error message:
 >  NX   Cannot find module '@nx/workspace/src/utils/fileutils'

**Comment by tinesoft** [comment] 2023-10-21 10:09
Hi @trondeh80 

Thank you for using my `nx-spring-boot` plugin.
It looks like you are using the latest version to date of Nx (v17.x.x), and apparently the mentioned  utility was (re)moved since.

I have create #195 to update all my plugins including the `nx-spring-boot` plugin  for full compatibility with Nx 17.

Please stay tuned!

**Comment by trondeh80** [comment] 2023-10-21 10:32
Great! I got it working by manually editing the import path in your js files in my node_modules folder. Thank you so much for creating such an awesome tool! :)

**Comment by tinesoft** [comment] 2023-10-21 10:53
Thanks for the kind words @trondeh80  :-)

I'm glad it's useful to you! 
Don't hesitate to show your support by giving a ⭐ to the  project on Github ;-)

**Comment by tinesoft** [comment] 2023-10-22 17:55
@trondeh80  Fixed and released in https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv9.0.0

**Comment by trondeh80** [comment] 2023-10-22 18:02
Brilliant! Huge thanks! I starred your repo!
